In [1]:
import numpy as np
import pandas as pd

scores = pd.DataFrame(np.random.randint(50,101,size=(50,5)),
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index=range(1,51))
scores

     國文   英文   數學   地理  歷史
1    67   81   74   77  93
2    82   79   98   51  53
3    92  100   92   88  62
4    67   56   51   54  73
5    85   81   65   60  85
6    62   69   89   75  75
7    97   68   55   60  50
8    54   80   57   89  72
9    75   57   81   80  55
10   59   59   50   94  57
11   63   62   67   51  88
12   50   67   64   94  63
13   64   81  100   77  56
14  100   82   81   65  58
15   64   71   51   53  71
16   81   77   85   83  68
17   98   97   54   82  83
18   92   52   56   60  77
19   54   60   95   87  87
20   59   90  100   71  75
21   65  100   51   92  99
22   58   50   96   59  72
23   69   61   80   53  57
24   99   55   89  100  67
25   85   61   58   78  65
26   66   97   51   99  50
27   79   74   76   59  57
28   66   95  100   80  94
29   57   74   79   63  72
30   95   82   88   59  77
31   81   56   53   55  96
32   65  100   97   64  52
33   75   66   89   84  50
34   81   91   84   62  56
35   72   89   54   96  99
36   97   74   82   99  82
37   83   72   66   70  52
38   66   70   51   60  61
39   57   75   72   95  75
40   66   78   59   70  59
41   71   95   51   88  99
42   52   90   90   52  57
43   55   51   65   87  80
44   57   77   60   79  97
45   62   69   81   52  67
46   78   92   57   55  94
47   85   91   77   90  83
48   61   98   83   97  92
49   68   85   71   51  61
50   81  100   82   89  85

In [2]:
def abc(s):
    return s.max()
scores.apply(abc)

國文    100
英文    100
數學    100
地理    100
歷史     99
dtype: int64

In [3]:
def abc(s):
    return pd.Series([s.min(),s.max(),s.mean()],index=['最低分','最高分','平均'])
scores.apply(abc)

         國文      英文      數學      地理     歷史
最低分   50.00   50.00   50.00   51.00  50.00
最高分  100.00  100.00  100.00  100.00  99.00
平均    72.34   76.74   73.14   73.76  72.16

In [4]:
scores.index = scores.index.map(lambda i:f'{i}號')
scores

      國文   英文   數學   地理  歷史
1號    67   81   74   77  93
2號    82   79   98   51  53
3號    92  100   92   88  62
4號    67   56   51   54  73
5號    85   81   65   60  85
6號    62   69   89   75  75
7號    97   68   55   60  50
8號    54   80   57   89  72
9號    75   57   81   80  55
10號   59   59   50   94  57
11號   63   62   67   51  88
12號   50   67   64   94  63
13號   64   81  100   77  56
14號  100   82   81   65  58
15號   64   71   51   53  71
16號   81   77   85   83  68
17號   98   97   54   82  83
18號   92   52   56   60  77
19號   54   60   95   87  87
20號   59   90  100   71  75
21號   65  100   51   92  99
22號   58   50   96   59  72
23號   69   61   80   53  57
24號   99   55   89  100  67
25號   85   61   58   78  65
26號   66   97   51   99  50
27號   79   74   76   59  57
28號   66   95  100   80  94
29號   57   74   79   63  72
30號   95   82   88   59  77
31號   81   56   53   55  96
32號   65  100   97   64  52
33號   75   66   89   84  50
34號   81   91   84   62  56
35號   72   89   54   96  99
36號   97   74   82   99  82
37號   83   72   66   70  52
38號   66   70   51   60  61
39號   57   75   72   95  75
40號   66   78   59   70  59
41號   71   95   51   88  99
42號   52   90   90   52  57
43號   55   51   65   87  80
44號   57   77   60   79  97
45號   62   69   81   52  67
46號   78   92   57   55  94
47號   85   91   77   90  83
48號   61   98   83   97  92
49號   68   85   71   51  61
50號   81  100   82   89  85

In [8]:
def abc1(item):
    less_student = item[item < 60]
    less_count = less_student.count()
    less_str = ",".join(less_student.index.values.tolist())
    
    return pd.Series([item.sum(),item.mean(),less_count,less_str],index=['總分','平均','不及格科目數','不及格科目'])
scores.apply(abc1,axis=1)

      總分    平均  不及格科目數        不及格科目
1號   392  78.4       0
2號   363  72.6       2        地理,歷史
3號   434  86.8       0
4號   301  60.2       3     英文,數學,地理
5號   376  75.2       0
6號   370  74.0       0
7號   330  66.0       2        數學,歷史
8號   352  70.4       2        國文,數學
9號   348  69.6       2        英文,歷史
10號  319  63.8       4  國文,英文,數學,歷史
11號  331  66.2       1           地理
12號  338  67.6       1           國文
13號  378  75.6       1           歷史
14號  386  77.2       1           歷史
15號  310  62.0       2        數學,地理
16號  394  78.8       0
17號  414  82.8       1           數學
18號  337  67.4       2        英文,數學
19號  383  76.6       1           國文
20號  395  79.0       1           國文
21號  407  81.4       1           數學
22號  335  67.0       3     國文,英文,地理
23號  320  64.0       2        地理,歷史
24號  410  82.0       1           英文
25號  347  69.4       1           數學
26號  363  72.6       2        數學,歷史
27號  345  69.0       2        地理,歷史
28號  435  87.0       0
29號  345  69.0       1           國文
30號  401  80.2       1           地理
31號  341  68.2       3     英文,數學,地理
32號  378  75.6       1           歷史
33號  364  72.8       1           歷史
34號  374  74.8       1           歷史
35號  410  82.0       1           數學
36號  434  86.8       0
37號  343  68.6       1           歷史
38號  308  61.6       1           數學
39號  374  74.8       1           國文
40號  332  66.4       2        數學,歷史
41號  404  80.8       1           數學
42號  341  68.2       3     國文,地理,歷史
43號  338  67.6       2        國文,英文
44號  370  74.0       1           國文
45號  331  66.2       1           地理
46號  376  75.2       2        數學,地理
47號  426  85.2       0
48號  431  86.2       0
49號  336  67.2       1           地理
50號  437  87.4       0

In [9]:
one_student = scores.iloc[0]
less_student = one_student[one_student < 60]
less_student

Series([], Name: 1號, dtype: int64)

In [7]:
less_student.count()
",".join(less_student.index.values.tolist())

''